# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oppia', '0009_auto_20150524_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'date created')),
                ('school_code', models.TextField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Code',
                'verbose_name_plural': 'School Codes',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_town',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_group',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
