# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0010_auto_20160121_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcode',
            name='region',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolcode',
            name='school_type',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
