# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0011_auto_20160121_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='school_code',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
