# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0013_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_tag',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
