# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0016_userprofile_survey_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baselinesurvey',
            options={'verbose_name': 'BaselineSurvey', 'verbose_name_plural': 'BaselineSurveys'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
