# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0019_auto_20160601_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppia.SchoolCode'),
        ),
    ]
