# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0021_auto_20160601_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='oppia.SchoolCode'),
            preserve_default=False,
        ),
    ]
